name: R-CMD-check
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: r-lib/actions/setup-r@v2
      - name: Install dependencies
        run: Rscript -e 'install.packages(c("testthat","survival","ggplot2"))'
      - name: Run tests
        run: Rscript -e 'testthat::test_dir("tests")'
